/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BindingStatusEnum = {
    Bound: "bound",
    Unbound: "unbound",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type BindingStatusEnum = (typeof BindingStatusEnum)[keyof typeof BindingStatusEnum];

export function instanceOfBindingStatusEnum(value: any): boolean {
    for (const key in BindingStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(BindingStatusEnum, key)) {
            if (BindingStatusEnum[key as keyof typeof BindingStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BindingStatusEnumFromJSON(json: any): BindingStatusEnum {
    return BindingStatusEnumFromJSONTyped(json, false);
}

export function BindingStatusEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): BindingStatusEnum {
    return json as BindingStatusEnum;
}

export function BindingStatusEnumToJSON(value?: BindingStatusEnum | null): any {
    return value as any;
}

export function BindingStatusEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): BindingStatusEnum {
    return value as BindingStatusEnum;
}
