/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BlockedPrioritiesEnum = {
    P0: "p0",
    P1: "p1",
    P2: "p2",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type BlockedPrioritiesEnum =
    (typeof BlockedPrioritiesEnum)[keyof typeof BlockedPrioritiesEnum];

export function instanceOfBlockedPrioritiesEnum(value: any): boolean {
    for (const key in BlockedPrioritiesEnum) {
        if (Object.prototype.hasOwnProperty.call(BlockedPrioritiesEnum, key)) {
            if (BlockedPrioritiesEnum[key as keyof typeof BlockedPrioritiesEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlockedPrioritiesEnumFromJSON(json: any): BlockedPrioritiesEnum {
    return BlockedPrioritiesEnumFromJSONTyped(json, false);
}

export function BlockedPrioritiesEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): BlockedPrioritiesEnum {
    return json as BlockedPrioritiesEnum;
}

export function BlockedPrioritiesEnumToJSON(value?: BlockedPrioritiesEnum | null): any {
    return value as any;
}

export function BlockedPrioritiesEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): BlockedPrioritiesEnum {
    return value as BlockedPrioritiesEnum;
}
