/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkDirectorySyncStatus } from "./DingTalkDirectorySyncStatus";
import {
    DingTalkDirectorySyncStatusFromJSON,
    DingTalkDirectorySyncStatusToJSON,
} from "./DingTalkDirectorySyncStatus";

/**
 *
 * @export
 * @interface DingTalkDirectoryStatus
 */
export interface DingTalkDirectoryStatus {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryStatus
     */
    sourceSlug: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectoryStatus
     */
    canChange: boolean;
    /**
     *
     * @type {Array<DingTalkDirectorySyncStatus>}
     * @memberof DingTalkDirectoryStatus
     */
    sync: Array<DingTalkDirectorySyncStatus>;
}

/**
 * Check if a given object implements the DingTalkDirectoryStatus interface.
 */
export function instanceOfDingTalkDirectoryStatus(value: object): value is DingTalkDirectoryStatus {
    if (!("sourceSlug" in value) || value["sourceSlug"] === undefined) return false;
    if (!("canChange" in value) || value["canChange"] === undefined) return false;
    if (!("sync" in value) || value["sync"] === undefined) return false;
    return true;
}

export function DingTalkDirectoryStatusFromJSON(json: any): DingTalkDirectoryStatus {
    return DingTalkDirectoryStatusFromJSONTyped(json, false);
}

export function DingTalkDirectoryStatusFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectoryStatus {
    if (json == null) {
        return json;
    }
    return {
        sourceSlug: json["source_slug"],
        canChange: json["can_change"],
        sync: (json["sync"] as Array<any>).map(DingTalkDirectorySyncStatusFromJSON),
    };
}

export function DingTalkDirectoryStatusToJSON(json: any): DingTalkDirectoryStatus {
    return DingTalkDirectoryStatusToJSONTyped(json, false);
}

export function DingTalkDirectoryStatusToJSONTyped(
    value?: DingTalkDirectoryStatus | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        source_slug: value["sourceSlug"],
        can_change: value["canChange"],
        sync: (value["sync"] as Array<any>).map(DingTalkDirectorySyncStatusToJSON),
    };
}
