/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DingTalkManagedUsersErrorCodeEnum = {
    SourceUnavailable: "source_unavailable",
    ManagerNotFound: "manager_not_found",
    BindingConflict: "binding_conflict",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type DingTalkManagedUsersErrorCodeEnum =
    (typeof DingTalkManagedUsersErrorCodeEnum)[keyof typeof DingTalkManagedUsersErrorCodeEnum];

export function instanceOfDingTalkManagedUsersErrorCodeEnum(value: any): boolean {
    for (const key in DingTalkManagedUsersErrorCodeEnum) {
        if (Object.prototype.hasOwnProperty.call(DingTalkManagedUsersErrorCodeEnum, key)) {
            if (
                DingTalkManagedUsersErrorCodeEnum[
                    key as keyof typeof DingTalkManagedUsersErrorCodeEnum
                ] === value
            ) {
                return true;
            }
        }
    }
    return false;
}

export function DingTalkManagedUsersErrorCodeEnumFromJSON(
    json: any,
): DingTalkManagedUsersErrorCodeEnum {
    return DingTalkManagedUsersErrorCodeEnumFromJSONTyped(json, false);
}

export function DingTalkManagedUsersErrorCodeEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUsersErrorCodeEnum {
    return json as DingTalkManagedUsersErrorCodeEnum;
}

export function DingTalkManagedUsersErrorCodeEnumToJSON(
    value?: DingTalkManagedUsersErrorCodeEnum | null,
): any {
    return value as any;
}

export function DingTalkManagedUsersErrorCodeEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUsersErrorCodeEnum {
    return value as DingTalkManagedUsersErrorCodeEnum;
}
