/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkUsageBucket } from "./DingTalkUsageBucket";
import { DingTalkUsageBucketFromJSON, DingTalkUsageBucketToJSON } from "./DingTalkUsageBucket";

/**
 *
 * @export
 * @interface DingTalkDirectoryUsageResponse
 */
export interface DingTalkDirectoryUsageResponse {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUsageResponse
     */
    generatedAt: string;
    /**
     *
     * @type {Array<DingTalkUsageBucket>}
     * @memberof DingTalkDirectoryUsageResponse
     */
    buckets: Array<DingTalkUsageBucket>;
}

/**
 * Check if a given object implements the DingTalkDirectoryUsageResponse interface.
 */
export function instanceOfDingTalkDirectoryUsageResponse(
    value: object,
): value is DingTalkDirectoryUsageResponse {
    if (
        (!("generatedAt" in (value as Record<string, any>)) &&
            !("generated_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["generatedAt"] === undefined &&
            (value as Record<string, any>)["generated_at"] === undefined)
    )
        return false;
    if (!("buckets" in value) || value["buckets"] === undefined) return false;
    return true;
}

export function DingTalkDirectoryUsageResponseFromJSON(json: any): DingTalkDirectoryUsageResponse {
    return DingTalkDirectoryUsageResponseFromJSONTyped(json, false);
}

export function DingTalkDirectoryUsageResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectoryUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        generatedAt: json["generated_at"],
        buckets: (json["buckets"] as Array<any>).map(DingTalkUsageBucketFromJSON),
    };
}

export function DingTalkDirectoryUsageResponseToJSON(json: any): DingTalkDirectoryUsageResponse {
    return DingTalkDirectoryUsageResponseToJSONTyped(json, false);
}

export function DingTalkDirectoryUsageResponseToJSONTyped(
    value?: DingTalkDirectoryUsageResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        generated_at: value["generatedAt"],
        buckets: (value["buckets"] as Array<any>).map(DingTalkUsageBucketToJSON),
    };
}
