/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkDirectorySyncStatusStatusEnum } from "./DingTalkDirectorySyncStatusStatusEnum";
import {
    DingTalkDirectorySyncStatusStatusEnumFromJSON,
    DingTalkDirectorySyncStatusStatusEnumToJSON,
} from "./DingTalkDirectorySyncStatusStatusEnum";

/**
 *
 * @export
 * @interface DingTalkDirectorySyncStatus
 */
export interface DingTalkDirectorySyncStatus {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    corpId: string;
    /**
     *
     * @type {DingTalkDirectorySyncStatusStatusEnum}
     * @memberof DingTalkDirectorySyncStatus
     */
    status: DingTalkDirectorySyncStatusStatusEnum;
    /**
     *
     * @type {number}
     * @memberof DingTalkDirectorySyncStatus
     */
    generation?: number;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectorySyncStatus
     */
    startedAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectorySyncStatus
     */
    finishedAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectorySyncStatus
     */
    lastAttemptAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectorySyncStatus
     */
    lastSuccessAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    error?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    errorCode?: string;
    /**
     *
     * @type {any}
     * @memberof DingTalkDirectorySyncStatus
     */
    errorParams?: any | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    errorCorrelationId?: string | null;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof DingTalkDirectorySyncStatus
     */
    counters: { [key: string]: any };
}

/**
 * Check if a given object implements the DingTalkDirectorySyncStatus interface.
 */
export function instanceOfDingTalkDirectorySyncStatus(
    value: object,
): value is DingTalkDirectorySyncStatus {
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    if (!("status" in value) || value["status"] === undefined) return false;
    if (!("counters" in value) || value["counters"] === undefined) return false;
    return true;
}

export function DingTalkDirectorySyncStatusFromJSON(json: any): DingTalkDirectorySyncStatus {
    return DingTalkDirectorySyncStatusFromJSONTyped(json, false);
}

export function DingTalkDirectorySyncStatusFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncStatus {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
        status: DingTalkDirectorySyncStatusStatusEnumFromJSON(json["status"]),
        generation: json["generation"] == null ? undefined : json["generation"],
        startedAt: json["started_at"] == null ? undefined : new Date(json["started_at"]),
        finishedAt: json["finished_at"] == null ? undefined : new Date(json["finished_at"]),
        lastAttemptAt:
            json["last_attempt_at"] == null ? undefined : new Date(json["last_attempt_at"]),
        lastSuccessAt:
            json["last_success_at"] == null ? undefined : new Date(json["last_success_at"]),
        error: json["error"] == null ? undefined : json["error"],
        errorCode: json["error_code"] == null ? undefined : json["error_code"],
        errorParams: json["error_params"] == null ? undefined : json["error_params"],
        errorCorrelationId:
            json["error_correlation_id"] == null ? undefined : json["error_correlation_id"],
        counters: json["counters"],
    };
}

export function DingTalkDirectorySyncStatusToJSON(json: any): DingTalkDirectorySyncStatus {
    return DingTalkDirectorySyncStatusToJSONTyped(json, false);
}

export function DingTalkDirectorySyncStatusToJSONTyped(
    value?: DingTalkDirectorySyncStatus | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
        status: DingTalkDirectorySyncStatusStatusEnumToJSON(value["status"]),
        generation: value["generation"],
        started_at:
            value["startedAt"] == null ? value["startedAt"] : value["startedAt"].toISOString(),
        finished_at:
            value["finishedAt"] == null ? value["finishedAt"] : value["finishedAt"].toISOString(),
        last_attempt_at:
            value["lastAttemptAt"] == null
                ? value["lastAttemptAt"]
                : value["lastAttemptAt"].toISOString(),
        last_success_at:
            value["lastSuccessAt"] == null
                ? value["lastSuccessAt"]
                : value["lastSuccessAt"].toISOString(),
        error: value["error"],
        error_code: value["errorCode"],
        error_params: value["errorParams"],
        error_correlation_id: value["errorCorrelationId"],
        counters: value["counters"],
    };
}
