/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BindingStatusEnum } from "./BindingStatusEnum";
import { BindingStatusEnumFromJSON, BindingStatusEnumToJSON } from "./BindingStatusEnum";

/**
 *
 * @export
 * @interface DingTalkManagedUser
 */
export interface DingTalkManagedUser {
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    sourceUserId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    sourceIdentifier: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUser
     */
    directoryActive: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUser
     */
    isDeleted: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    authentikSubject: string | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    authentikSubjectType: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUser
     */
    authentikUserActive: boolean | null;
    /**
     *
     * @type {BindingStatusEnum}
     * @memberof DingTalkManagedUser
     */
    bindingStatus: BindingStatusEnum;
    /**
     *
     * @type {any}
     * @memberof DingTalkManagedUser
     */
    diagnostics: any | null;
}

/**
 * Check if a given object implements the DingTalkManagedUser interface.
 */
export function instanceOfDingTalkManagedUser(value: object): value is DingTalkManagedUser {
    if (!("sourceUserId" in value) || value["sourceUserId"] === undefined) return false;
    if (!("sourceIdentifier" in value) || value["sourceIdentifier"] === undefined) return false;
    if (!("directoryActive" in value) || value["directoryActive"] === undefined) return false;
    if (!("isDeleted" in value) || value["isDeleted"] === undefined) return false;
    if (!("authentikSubject" in value) || value["authentikSubject"] === undefined) return false;
    if (!("authentikSubjectType" in value) || value["authentikSubjectType"] === undefined)
        return false;
    if (!("authentikUserActive" in value) || value["authentikUserActive"] === undefined)
        return false;
    if (!("bindingStatus" in value) || value["bindingStatus"] === undefined) return false;
    if (!("diagnostics" in value) || value["diagnostics"] === undefined) return false;
    return true;
}

export function DingTalkManagedUserFromJSON(json: any): DingTalkManagedUser {
    return DingTalkManagedUserFromJSONTyped(json, false);
}

export function DingTalkManagedUserFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUser {
    if (json == null) {
        return json;
    }
    return {
        sourceUserId: json["source_user_id"],
        sourceIdentifier: json["source_identifier"],
        directoryActive: json["directory_active"],
        isDeleted: json["is_deleted"],
        authentikSubject: json["authentik_subject"],
        authentikSubjectType: json["authentik_subject_type"],
        authentikUserActive: json["authentik_user_active"],
        bindingStatus: BindingStatusEnumFromJSON(json["binding_status"]),
        diagnostics: json["diagnostics"],
    };
}

export function DingTalkManagedUserToJSON(json: any): DingTalkManagedUser {
    return DingTalkManagedUserToJSONTyped(json, false);
}

export function DingTalkManagedUserToJSONTyped(
    value?: DingTalkManagedUser | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        source_user_id: value["sourceUserId"],
        source_identifier: value["sourceIdentifier"],
        directory_active: value["directoryActive"],
        is_deleted: value["isDeleted"],
        authentik_subject: value["authentikSubject"],
        authentik_subject_type: value["authentikSubjectType"],
        authentik_user_active: value["authentikUserActive"],
        binding_status: BindingStatusEnumToJSON(value["bindingStatus"]),
        diagnostics: value["diagnostics"],
    };
}
