/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectorySyncRequestRequest
 */
export interface DingTalkDirectorySyncRequestRequest {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncRequestRequest
     */
    corpId: string;
}

/**
 * Check if a given object implements the DingTalkDirectorySyncRequestRequest interface.
 */
export function instanceOfDingTalkDirectorySyncRequestRequest(
    value: object,
): value is DingTalkDirectorySyncRequestRequest {
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    return true;
}

export function DingTalkDirectorySyncRequestRequestFromJSON(
    json: any,
): DingTalkDirectorySyncRequestRequest {
    return DingTalkDirectorySyncRequestRequestFromJSONTyped(json, false);
}

export function DingTalkDirectorySyncRequestRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
    };
}

export function DingTalkDirectorySyncRequestRequestToJSON(
    json: any,
): DingTalkDirectorySyncRequestRequest {
    return DingTalkDirectorySyncRequestRequestToJSONTyped(json, false);
}

export function DingTalkDirectorySyncRequestRequestToJSONTyped(
    value?: DingTalkDirectorySyncRequestRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
    };
}
