/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectoryUser
 */
export interface DingTalkDirectoryUser {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    corpId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    userId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    avatar?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    mobile?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    jobNumber?: string;
    /**
     *
     * @type {any}
     * @memberof DingTalkDirectoryUser
     */
    deptIdList?: any | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryUser
     */
    managerUserId?: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectoryUser
     */
    active?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectoryUser
     */
    isDeleted?: boolean;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectoryUser
     */
    lastSeenAt: Date;
}

/**
 * Check if a given object implements the DingTalkDirectoryUser interface.
 */
export function instanceOfDingTalkDirectoryUser(value: object): value is DingTalkDirectoryUser {
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    if (!("userId" in value) || value["userId"] === undefined) return false;
    if (!("lastSeenAt" in value) || value["lastSeenAt"] === undefined) return false;
    return true;
}

export function DingTalkDirectoryUserFromJSON(json: any): DingTalkDirectoryUser {
    return DingTalkDirectoryUserFromJSONTyped(json, false);
}

export function DingTalkDirectoryUserFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectoryUser {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
        userId: json["user_id"],
        name: json["name"] == null ? undefined : json["name"],
        title: json["title"] == null ? undefined : json["title"],
        avatar: json["avatar"] == null ? undefined : json["avatar"],
        email: json["email"] == null ? undefined : json["email"],
        mobile: json["mobile"] == null ? undefined : json["mobile"],
        jobNumber: json["job_number"] == null ? undefined : json["job_number"],
        deptIdList: json["dept_id_list"] == null ? undefined : json["dept_id_list"],
        managerUserId: json["manager_user_id"] == null ? undefined : json["manager_user_id"],
        active: json["active"] == null ? undefined : json["active"],
        isDeleted: json["is_deleted"] == null ? undefined : json["is_deleted"],
        lastSeenAt: new Date(json["last_seen_at"]),
    };
}

export function DingTalkDirectoryUserToJSON(json: any): DingTalkDirectoryUser {
    return DingTalkDirectoryUserToJSONTyped(json, false);
}

export function DingTalkDirectoryUserToJSONTyped(
    value?: DingTalkDirectoryUser | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
        user_id: value["userId"],
        name: value["name"],
        title: value["title"],
        avatar: value["avatar"],
        email: value["email"],
        mobile: value["mobile"],
        job_number: value["jobNumber"],
        dept_id_list: value["deptIdList"],
        manager_user_id: value["managerUserId"],
        active: value["active"],
        is_deleted: value["isDeleted"],
        last_seen_at: value["lastSeenAt"].toISOString(),
    };
}
