/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlockedPrioritiesEnum } from "./BlockedPrioritiesEnum";
import {
    BlockedPrioritiesEnumFromJSON,
    BlockedPrioritiesEnumToJSON,
} from "./BlockedPrioritiesEnum";

/**
 *
 * @export
 * @interface DingTalkDirectoryUsagePolicy
 */
export interface DingTalkDirectoryUsagePolicy {
    /**
     *
     * @type {Array<BlockedPrioritiesEnum>}
     * @memberof DingTalkDirectoryUsagePolicy
     */
    blockedPriorities: Array<BlockedPrioritiesEnum>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof DingTalkDirectoryUsagePolicy
     */
    throttlePerHour: { [key: string]: any };
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectoryUsagePolicy
     */
    blockP0Billed: boolean;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectoryUsagePolicy
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the DingTalkDirectoryUsagePolicy interface.
 */
export function instanceOfDingTalkDirectoryUsagePolicy(
    value: object,
): value is DingTalkDirectoryUsagePolicy {
    if (
        (!("blockedPriorities" in (value as Record<string, any>)) &&
            !("blocked_priorities" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["blockedPriorities"] === undefined &&
            (value as Record<string, any>)["blocked_priorities"] === undefined)
    )
        return false;
    if (
        (!("throttlePerHour" in (value as Record<string, any>)) &&
            !("throttle_per_hour" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["throttlePerHour"] === undefined &&
            (value as Record<string, any>)["throttle_per_hour"] === undefined)
    )
        return false;
    if (
        (!("blockP0Billed" in (value as Record<string, any>)) &&
            !("block_p0_billed" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["blockP0Billed"] === undefined &&
            (value as Record<string, any>)["block_p0_billed"] === undefined)
    )
        return false;
    if (
        (!("expiresAt" in (value as Record<string, any>)) &&
            !("expires_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["expiresAt"] === undefined &&
            (value as Record<string, any>)["expires_at"] === undefined)
    )
        return false;
    return true;
}

export function DingTalkDirectoryUsagePolicyFromJSON(json: any): DingTalkDirectoryUsagePolicy {
    return DingTalkDirectoryUsagePolicyFromJSONTyped(json, false);
}

export function DingTalkDirectoryUsagePolicyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectoryUsagePolicy {
    if (json == null) {
        return json;
    }
    return {
        blockedPriorities: (json["blocked_priorities"] as Array<any>).map(
            BlockedPrioritiesEnumFromJSON,
        ),
        throttlePerHour: json["throttle_per_hour"],
        blockP0Billed: json["block_p0_billed"],
        expiresAt: new Date(json["expires_at"]),
    };
}

export function DingTalkDirectoryUsagePolicyToJSON(json: any): DingTalkDirectoryUsagePolicy {
    return DingTalkDirectoryUsagePolicyToJSONTyped(json, false);
}

export function DingTalkDirectoryUsagePolicyToJSONTyped(
    value?: DingTalkDirectoryUsagePolicy | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        blocked_priorities: (value["blockedPriorities"] as Array<any>).map(
            BlockedPrioritiesEnumToJSON,
        ),
        throttle_per_hour: value["throttlePerHour"],
        block_p0_billed: value["blockP0Billed"],
        expires_at: value["expiresAt"].toISOString(),
    };
}
