/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistDepartmentsResponse
 */
export interface DingTalkAllowlistDepartmentsResponse {
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistDepartmentsResponse
     */
    corpId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistDepartmentsResponse
     */
    label?: string;
    /**
     *
     * @type {any}
     * @memberof DingTalkAllowlistDepartmentsResponse
     */
    departments: any | null;
}

/**
 * Check if a given object implements the DingTalkAllowlistDepartmentsResponse interface.
 */
export function instanceOfDingTalkAllowlistDepartmentsResponse(
    value: object,
): value is DingTalkAllowlistDepartmentsResponse {
    if (
        (!("corpId" in (value as Record<string, any>)) &&
            !("corp_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["corpId"] === undefined &&
            (value as Record<string, any>)["corp_id"] === undefined)
    )
        return false;
    if (!("departments" in value) || value["departments"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistDepartmentsResponseFromJSON(
    json: any,
): DingTalkAllowlistDepartmentsResponse {
    return DingTalkAllowlistDepartmentsResponseFromJSONTyped(json, false);
}

export function DingTalkAllowlistDepartmentsResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistDepartmentsResponse {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
        label: json["label"] == null ? undefined : json["label"],
        departments: json["departments"],
    };
}

export function DingTalkAllowlistDepartmentsResponseToJSON(
    json: any,
): DingTalkAllowlistDepartmentsResponse {
    return DingTalkAllowlistDepartmentsResponseToJSONTyped(json, false);
}

export function DingTalkAllowlistDepartmentsResponseToJSONTyped(
    value?: DingTalkAllowlistDepartmentsResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
        label: value["label"],
        departments: value["departments"],
    };
}
