/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistManagedPolicy
 */
export interface DingTalkAllowlistManagedPolicy {
    /**
     *
     * @type {boolean}
     * @memberof DingTalkAllowlistManagedPolicy
     */
    _exists: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistManagedPolicy
     */
    pk: string | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistManagedPolicy
     */
    name: string | null;
}

/**
 * Check if a given object implements the DingTalkAllowlistManagedPolicy interface.
 */
export function instanceOfDingTalkAllowlistManagedPolicy(
    value: object,
): value is DingTalkAllowlistManagedPolicy {
    if (!("_exists" in value) || value["_exists"] === undefined) return false;
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistManagedPolicyFromJSON(json: any): DingTalkAllowlistManagedPolicy {
    return DingTalkAllowlistManagedPolicyFromJSONTyped(json, false);
}

export function DingTalkAllowlistManagedPolicyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistManagedPolicy {
    if (json == null) {
        return json;
    }
    return {
        _exists: json["exists"],
        pk: json["pk"],
        name: json["name"],
    };
}

export function DingTalkAllowlistManagedPolicyToJSON(json: any): DingTalkAllowlistManagedPolicy {
    return DingTalkAllowlistManagedPolicyToJSONTyped(json, false);
}

export function DingTalkAllowlistManagedPolicyToJSONTyped(
    value?: DingTalkAllowlistManagedPolicy | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        exists: value["_exists"],
        pk: value["pk"],
        name: value["name"],
    };
}
