/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistSourceLinkGuard
 */
export interface DingTalkAllowlistSourceLinkGuard {
    /**
     *
     * @type {boolean}
     * @memberof DingTalkAllowlistSourceLinkGuard
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the DingTalkAllowlistSourceLinkGuard interface.
 */
export function instanceOfDingTalkAllowlistSourceLinkGuard(
    value: object,
): value is DingTalkAllowlistSourceLinkGuard {
    if (!("enabled" in value) || value["enabled"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistSourceLinkGuardFromJSON(
    json: any,
): DingTalkAllowlistSourceLinkGuard {
    return DingTalkAllowlistSourceLinkGuardFromJSONTyped(json, false);
}

export function DingTalkAllowlistSourceLinkGuardFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistSourceLinkGuard {
    if (json == null) {
        return json;
    }
    return {
        enabled: json["enabled"],
    };
}

export function DingTalkAllowlistSourceLinkGuardToJSON(
    json: any,
): DingTalkAllowlistSourceLinkGuard {
    return DingTalkAllowlistSourceLinkGuardToJSONTyped(json, false);
}

export function DingTalkAllowlistSourceLinkGuardToJSONTyped(
    value?: DingTalkAllowlistSourceLinkGuard | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        enabled: value["enabled"],
    };
}
