/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BindingStatusEnum } from "./BindingStatusEnum";
import { BindingStatusEnumFromJSON, BindingStatusEnumToJSON } from "./BindingStatusEnum";

/**
 *
 * @export
 * @interface DingTalkManagedUser
 */
export interface DingTalkManagedUser {
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    sourceUserId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    sourceIdentifier: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUser
     */
    directoryActive: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUser
     */
    isDeleted: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    authentikSubject: string | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUser
     */
    authentikSubjectType: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUser
     */
    authentikUserActive: boolean | null;
    /**
     *
     * @type {BindingStatusEnum}
     * @memberof DingTalkManagedUser
     */
    bindingStatus: BindingStatusEnum;
    /**
     *
     * @type {any}
     * @memberof DingTalkManagedUser
     */
    diagnostics: any | null;
}

/**
 * Check if a given object implements the DingTalkManagedUser interface.
 */
export function instanceOfDingTalkManagedUser(value: object): value is DingTalkManagedUser {
    if (
        (!("sourceUserId" in (value as Record<string, any>)) &&
            !("source_user_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["sourceUserId"] === undefined &&
            (value as Record<string, any>)["source_user_id"] === undefined)
    )
        return false;
    if (
        (!("sourceIdentifier" in (value as Record<string, any>)) &&
            !("source_identifier" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["sourceIdentifier"] === undefined &&
            (value as Record<string, any>)["source_identifier"] === undefined)
    )
        return false;
    if (
        (!("directoryActive" in (value as Record<string, any>)) &&
            !("directory_active" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["directoryActive"] === undefined &&
            (value as Record<string, any>)["directory_active"] === undefined)
    )
        return false;
    if (
        (!("isDeleted" in (value as Record<string, any>)) &&
            !("is_deleted" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["isDeleted"] === undefined &&
            (value as Record<string, any>)["is_deleted"] === undefined)
    )
        return false;
    if (
        (!("authentikSubject" in (value as Record<string, any>)) &&
            !("authentik_subject" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["authentikSubject"] === undefined &&
            (value as Record<string, any>)["authentik_subject"] === undefined)
    )
        return false;
    if (
        (!("authentikSubjectType" in (value as Record<string, any>)) &&
            !("authentik_subject_type" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["authentikSubjectType"] === undefined &&
            (value as Record<string, any>)["authentik_subject_type"] === undefined)
    )
        return false;
    if (
        (!("authentikUserActive" in (value as Record<string, any>)) &&
            !("authentik_user_active" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["authentikUserActive"] === undefined &&
            (value as Record<string, any>)["authentik_user_active"] === undefined)
    )
        return false;
    if (
        (!("bindingStatus" in (value as Record<string, any>)) &&
            !("binding_status" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["bindingStatus"] === undefined &&
            (value as Record<string, any>)["binding_status"] === undefined)
    )
        return false;
    if (!("diagnostics" in value) || value["diagnostics"] === undefined) return false;
    return true;
}

export function DingTalkManagedUserFromJSON(json: any): DingTalkManagedUser {
    return DingTalkManagedUserFromJSONTyped(json, false);
}

export function DingTalkManagedUserFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUser {
    if (json == null) {
        return json;
    }
    return {
        sourceUserId: json["source_user_id"],
        sourceIdentifier: json["source_identifier"],
        directoryActive: json["directory_active"],
        isDeleted: json["is_deleted"],
        authentikSubject: json["authentik_subject"],
        authentikSubjectType: json["authentik_subject_type"],
        authentikUserActive: json["authentik_user_active"],
        bindingStatus: BindingStatusEnumFromJSON(json["binding_status"]),
        diagnostics: json["diagnostics"],
    };
}

export function DingTalkManagedUserToJSON(json: any): DingTalkManagedUser {
    return DingTalkManagedUserToJSONTyped(json, false);
}

export function DingTalkManagedUserToJSONTyped(
    value?: DingTalkManagedUser | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        source_user_id: value["sourceUserId"],
        source_identifier: value["sourceIdentifier"],
        directory_active: value["directoryActive"],
        is_deleted: value["isDeleted"],
        authentik_subject: value["authentikSubject"],
        authentik_subject_type: value["authentikSubjectType"],
        authentik_user_active: value["authentikUserActive"],
        binding_status: BindingStatusEnumToJSON(value["bindingStatus"]),
        diagnostics: value["diagnostics"],
    };
}
