/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectoryDepartment
 */
export interface DingTalkDirectoryDepartment {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryDepartment
     */
    corpId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryDepartment
     */
    deptId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryDepartment
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryDepartment
     */
    parentDeptId?: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectoryDepartment
     */
    isDeleted?: boolean;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectoryDepartment
     */
    lastSeenAt: Date;
}

/**
 * Check if a given object implements the DingTalkDirectoryDepartment interface.
 */
export function instanceOfDingTalkDirectoryDepartment(
    value: object,
): value is DingTalkDirectoryDepartment {
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    if (!("deptId" in value) || value["deptId"] === undefined) return false;
    if (!("lastSeenAt" in value) || value["lastSeenAt"] === undefined) return false;
    return true;
}

export function DingTalkDirectoryDepartmentFromJSON(json: any): DingTalkDirectoryDepartment {
    return DingTalkDirectoryDepartmentFromJSONTyped(json, false);
}

export function DingTalkDirectoryDepartmentFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectoryDepartment {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
        deptId: json["dept_id"],
        name: json["name"] == null ? undefined : json["name"],
        parentDeptId: json["parent_dept_id"] == null ? undefined : json["parent_dept_id"],
        isDeleted: json["is_deleted"] == null ? undefined : json["is_deleted"],
        lastSeenAt: new Date(json["last_seen_at"]),
    };
}

export function DingTalkDirectoryDepartmentToJSON(json: any): DingTalkDirectoryDepartment {
    return DingTalkDirectoryDepartmentToJSONTyped(json, false);
}

export function DingTalkDirectoryDepartmentToJSONTyped(
    value?: DingTalkDirectoryDepartment | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
        dept_id: value["deptId"],
        name: value["name"],
        parent_dept_id: value["parentDeptId"],
        is_deleted: value["isDeleted"],
        last_seen_at: value["lastSeenAt"].toISOString(),
    };
}
