/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistDepartmentsRequestRequest
 */
export interface DingTalkAllowlistDepartmentsRequestRequest {
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistDepartmentsRequestRequest
     */
    corpId?: string;
}

/**
 * Check if a given object implements the DingTalkAllowlistDepartmentsRequestRequest interface.
 */
export function instanceOfDingTalkAllowlistDepartmentsRequestRequest(
    value: object,
): value is DingTalkAllowlistDepartmentsRequestRequest {
    return true;
}

export function DingTalkAllowlistDepartmentsRequestRequestFromJSON(
    json: any,
): DingTalkAllowlistDepartmentsRequestRequest {
    return DingTalkAllowlistDepartmentsRequestRequestFromJSONTyped(json, false);
}

export function DingTalkAllowlistDepartmentsRequestRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistDepartmentsRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"] == null ? undefined : json["corp_id"],
    };
}

export function DingTalkAllowlistDepartmentsRequestRequestToJSON(
    json: any,
): DingTalkAllowlistDepartmentsRequestRequest {
    return DingTalkAllowlistDepartmentsRequestRequestToJSONTyped(json, false);
}

export function DingTalkAllowlistDepartmentsRequestRequestToJSONTyped(
    value?: DingTalkAllowlistDepartmentsRequestRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
    };
}
