/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectorySyncQueued
 */
export interface DingTalkDirectorySyncQueued {
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectorySyncQueued
     */
    queued: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncQueued
     */
    corpId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncQueued
     */
    runId: string | null;
}

/**
 * Check if a given object implements the DingTalkDirectorySyncQueued interface.
 */
export function instanceOfDingTalkDirectorySyncQueued(
    value: object,
): value is DingTalkDirectorySyncQueued {
    if (!("queued" in value) || value["queued"] === undefined) return false;
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    if (!("runId" in value) || value["runId"] === undefined) return false;
    return true;
}

export function DingTalkDirectorySyncQueuedFromJSON(json: any): DingTalkDirectorySyncQueued {
    return DingTalkDirectorySyncQueuedFromJSONTyped(json, false);
}

export function DingTalkDirectorySyncQueuedFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncQueued {
    if (json == null) {
        return json;
    }
    return {
        queued: json["queued"],
        corpId: json["corp_id"],
        runId: json["run_id"],
    };
}

export function DingTalkDirectorySyncQueuedToJSON(json: any): DingTalkDirectorySyncQueued {
    return DingTalkDirectorySyncQueuedToJSONTyped(json, false);
}

export function DingTalkDirectorySyncQueuedToJSONTyped(
    value?: DingTalkDirectorySyncQueued | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        queued: value["queued"],
        corp_id: value["corpId"],
        run_id: value["runId"],
    };
}
