/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkManagedUsersErrorCodeEnum } from "./DingTalkManagedUsersErrorCodeEnum";
import {
    DingTalkManagedUsersErrorCodeEnumFromJSON,
    DingTalkManagedUsersErrorCodeEnumToJSON,
} from "./DingTalkManagedUsersErrorCodeEnum";

/**
 *
 * @export
 * @interface DingTalkManagedUsersError
 */
export interface DingTalkManagedUsersError {
    /**
     *
     * @type {DingTalkManagedUsersErrorCodeEnum}
     * @memberof DingTalkManagedUsersError
     */
    code: DingTalkManagedUsersErrorCodeEnum;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersError
     */
    detail: string;
}

/**
 * Check if a given object implements the DingTalkManagedUsersError interface.
 */
export function instanceOfDingTalkManagedUsersError(
    value: object,
): value is DingTalkManagedUsersError {
    if (!("code" in value) || value["code"] === undefined) return false;
    if (!("detail" in value) || value["detail"] === undefined) return false;
    return true;
}

export function DingTalkManagedUsersErrorFromJSON(json: any): DingTalkManagedUsersError {
    return DingTalkManagedUsersErrorFromJSONTyped(json, false);
}

export function DingTalkManagedUsersErrorFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUsersError {
    if (json == null) {
        return json;
    }
    return {
        code: DingTalkManagedUsersErrorCodeEnumFromJSON(json["code"]),
        detail: json["detail"],
    };
}

export function DingTalkManagedUsersErrorToJSON(json: any): DingTalkManagedUsersError {
    return DingTalkManagedUsersErrorToJSONTyped(json, false);
}

export function DingTalkManagedUsersErrorToJSONTyped(
    value?: DingTalkManagedUsersError | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        code: DingTalkManagedUsersErrorCodeEnumToJSON(value["code"]),
        detail: value["detail"],
    };
}
