/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistDiscoverStartResponse
 */
export interface DingTalkAllowlistDiscoverStartResponse {
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistDiscoverStartResponse
     */
    state: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistDiscoverStartResponse
     */
    authorizationUrl: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistDiscoverStartResponse
     */
    url: string;
}

/**
 * Check if a given object implements the DingTalkAllowlistDiscoverStartResponse interface.
 */
export function instanceOfDingTalkAllowlistDiscoverStartResponse(
    value: object,
): value is DingTalkAllowlistDiscoverStartResponse {
    if (!("state" in value) || value["state"] === undefined) return false;
    if (!("authorizationUrl" in value) || value["authorizationUrl"] === undefined) return false;
    if (!("url" in value) || value["url"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistDiscoverStartResponseFromJSON(
    json: any,
): DingTalkAllowlistDiscoverStartResponse {
    return DingTalkAllowlistDiscoverStartResponseFromJSONTyped(json, false);
}

export function DingTalkAllowlistDiscoverStartResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistDiscoverStartResponse {
    if (json == null) {
        return json;
    }
    return {
        state: json["state"],
        authorizationUrl: json["authorization_url"],
        url: json["url"],
    };
}

export function DingTalkAllowlistDiscoverStartResponseToJSON(
    json: any,
): DingTalkAllowlistDiscoverStartResponse {
    return DingTalkAllowlistDiscoverStartResponseToJSONTyped(json, false);
}

export function DingTalkAllowlistDiscoverStartResponseToJSONTyped(
    value?: DingTalkAllowlistDiscoverStartResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        state: value["state"],
        authorization_url: value["authorizationUrl"],
        url: value["url"],
    };
}
