/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkManagedUser } from "./DingTalkManagedUser";
import { DingTalkManagedUserFromJSON, DingTalkManagedUserToJSON } from "./DingTalkManagedUser";
import type { DingTalkManagedUsersPagination } from "./DingTalkManagedUsersPagination";
import {
    DingTalkManagedUsersPaginationFromJSON,
    DingTalkManagedUsersPaginationToJSON,
} from "./DingTalkManagedUsersPagination";

/**
 *
 * @export
 * @interface DingTalkManagedUsersResponse
 */
export interface DingTalkManagedUsersResponse {
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersResponse
     */
    sourceSlug: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersResponse
     */
    corpId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersResponse
     */
    managerUserId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersResponse
     */
    resolver: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersResponse
     */
    resolvedAt: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkManagedUsersResponse
     */
    stale: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkManagedUsersResponse
     */
    lastSyncedAt: string | null;
    /**
     *
     * @type {any}
     * @memberof DingTalkManagedUsersResponse
     */
    diagnostics: any | null;
    /**
     *
     * @type {DingTalkManagedUsersPagination}
     * @memberof DingTalkManagedUsersResponse
     */
    pagination: DingTalkManagedUsersPagination;
    /**
     *
     * @type {Array<DingTalkManagedUser>}
     * @memberof DingTalkManagedUsersResponse
     */
    users: Array<DingTalkManagedUser>;
}

/**
 * Check if a given object implements the DingTalkManagedUsersResponse interface.
 */
export function instanceOfDingTalkManagedUsersResponse(
    value: object,
): value is DingTalkManagedUsersResponse {
    if (
        (!("sourceSlug" in (value as Record<string, any>)) &&
            !("source_slug" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["sourceSlug"] === undefined &&
            (value as Record<string, any>)["source_slug"] === undefined)
    )
        return false;
    if (
        (!("corpId" in (value as Record<string, any>)) &&
            !("corp_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["corpId"] === undefined &&
            (value as Record<string, any>)["corp_id"] === undefined)
    )
        return false;
    if (
        (!("managerUserId" in (value as Record<string, any>)) &&
            !("manager_user_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["managerUserId"] === undefined &&
            (value as Record<string, any>)["manager_user_id"] === undefined)
    )
        return false;
    if (!("resolver" in value) || value["resolver"] === undefined) return false;
    if (
        (!("resolvedAt" in (value as Record<string, any>)) &&
            !("resolved_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["resolvedAt"] === undefined &&
            (value as Record<string, any>)["resolved_at"] === undefined)
    )
        return false;
    if (!("stale" in value) || value["stale"] === undefined) return false;
    if (
        (!("lastSyncedAt" in (value as Record<string, any>)) &&
            !("last_synced_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["lastSyncedAt"] === undefined &&
            (value as Record<string, any>)["last_synced_at"] === undefined)
    )
        return false;
    if (!("diagnostics" in value) || value["diagnostics"] === undefined) return false;
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("users" in value) || value["users"] === undefined) return false;
    return true;
}

export function DingTalkManagedUsersResponseFromJSON(json: any): DingTalkManagedUsersResponse {
    return DingTalkManagedUsersResponseFromJSONTyped(json, false);
}

export function DingTalkManagedUsersResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        sourceSlug: json["source_slug"],
        corpId: json["corp_id"],
        managerUserId: json["manager_user_id"],
        resolver: json["resolver"],
        resolvedAt: json["resolved_at"],
        stale: json["stale"],
        lastSyncedAt: json["last_synced_at"],
        diagnostics: json["diagnostics"],
        pagination: DingTalkManagedUsersPaginationFromJSON(json["pagination"]),
        users: (json["users"] as Array<any>).map(DingTalkManagedUserFromJSON),
    };
}

export function DingTalkManagedUsersResponseToJSON(json: any): DingTalkManagedUsersResponse {
    return DingTalkManagedUsersResponseToJSONTyped(json, false);
}

export function DingTalkManagedUsersResponseToJSONTyped(
    value?: DingTalkManagedUsersResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        source_slug: value["sourceSlug"],
        corp_id: value["corpId"],
        manager_user_id: value["managerUserId"],
        resolver: value["resolver"],
        resolved_at: value["resolvedAt"],
        stale: value["stale"],
        last_synced_at: value["lastSyncedAt"],
        diagnostics: value["diagnostics"],
        pagination: DingTalkManagedUsersPaginationToJSON(value["pagination"]),
        users: (value["users"] as Array<any>).map(DingTalkManagedUserToJSON),
    };
}
