/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectorySyncDeleted
 */
export interface DingTalkDirectorySyncDeleted {
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectorySyncDeleted
     */
    deleted: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncDeleted
     */
    corpId: string;
}

/**
 * Check if a given object implements the DingTalkDirectorySyncDeleted interface.
 */
export function instanceOfDingTalkDirectorySyncDeleted(
    value: object,
): value is DingTalkDirectorySyncDeleted {
    if (!("deleted" in value) || value["deleted"] === undefined) return false;
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    return true;
}

export function DingTalkDirectorySyncDeletedFromJSON(json: any): DingTalkDirectorySyncDeleted {
    return DingTalkDirectorySyncDeletedFromJSONTyped(json, false);
}

export function DingTalkDirectorySyncDeletedFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncDeleted {
    if (json == null) {
        return json;
    }
    return {
        deleted: json["deleted"],
        corpId: json["corp_id"],
    };
}

export function DingTalkDirectorySyncDeletedToJSON(json: any): DingTalkDirectorySyncDeleted {
    return DingTalkDirectorySyncDeletedToJSONTyped(json, false);
}

export function DingTalkDirectorySyncDeletedToJSONTyped(
    value?: DingTalkDirectorySyncDeleted | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        deleted: value["deleted"],
        corp_id: value["corpId"],
    };
}
