/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DingTalkDirectorySyncStatusStatusEnum = {
    Unknown: "unknown",
    Queued: "queued",
    Running: "running",
    Success: "success",
    Error: "error",
    Deleted: "deleted",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type DingTalkDirectorySyncStatusStatusEnum =
    (typeof DingTalkDirectorySyncStatusStatusEnum)[keyof typeof DingTalkDirectorySyncStatusStatusEnum];

export function instanceOfDingTalkDirectorySyncStatusStatusEnum(value: any): boolean {
    for (const key in DingTalkDirectorySyncStatusStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(DingTalkDirectorySyncStatusStatusEnum, key)) {
            if (
                DingTalkDirectorySyncStatusStatusEnum[
                    key as keyof typeof DingTalkDirectorySyncStatusStatusEnum
                ] === value
            ) {
                return true;
            }
        }
    }
    return false;
}

export function DingTalkDirectorySyncStatusStatusEnumFromJSON(
    json: any,
): DingTalkDirectorySyncStatusStatusEnum {
    return DingTalkDirectorySyncStatusStatusEnumFromJSONTyped(json, false);
}

export function DingTalkDirectorySyncStatusStatusEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncStatusStatusEnum {
    return json as DingTalkDirectorySyncStatusStatusEnum;
}

export function DingTalkDirectorySyncStatusStatusEnumToJSON(
    value?: DingTalkDirectorySyncStatusStatusEnum | null,
): any {
    return value as any;
}

export function DingTalkDirectorySyncStatusStatusEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncStatusStatusEnum {
    return value as DingTalkDirectorySyncStatusStatusEnum;
}
