/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkAllowlistManagedPolicy } from "./DingTalkAllowlistManagedPolicy";
import {
    DingTalkAllowlistManagedPolicyFromJSON,
    DingTalkAllowlistManagedPolicyToJSON,
} from "./DingTalkAllowlistManagedPolicy";
import type { DingTalkAllowlistPolicyBinding } from "./DingTalkAllowlistPolicyBinding";
import {
    DingTalkAllowlistPolicyBindingFromJSON,
    DingTalkAllowlistPolicyBindingToJSON,
} from "./DingTalkAllowlistPolicyBinding";
import type { DingTalkAllowlistSourceLinkGuard } from "./DingTalkAllowlistSourceLinkGuard";
import {
    DingTalkAllowlistSourceLinkGuardFromJSON,
    DingTalkAllowlistSourceLinkGuardToJSON,
} from "./DingTalkAllowlistSourceLinkGuard";

/**
 *
 * @export
 * @interface DingTalkAllowlistStatusResponse
 */
export interface DingTalkAllowlistStatusResponse {
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistStatusResponse
     */
    revision: string;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkAllowlistStatusResponse
     */
    canManage: boolean;
    /**
     *
     * @type {any}
     * @memberof DingTalkAllowlistStatusResponse
     */
    config: any | null;
    /**
     *
     * @type {DingTalkAllowlistManagedPolicy}
     * @memberof DingTalkAllowlistStatusResponse
     */
    managedPolicy: DingTalkAllowlistManagedPolicy;
    /**
     *
     * @type {DingTalkAllowlistPolicyBinding}
     * @memberof DingTalkAllowlistStatusResponse
     */
    policyBinding: DingTalkAllowlistPolicyBinding;
    /**
     *
     * @type {Array<DingTalkAllowlistPolicyBinding>}
     * @memberof DingTalkAllowlistStatusResponse
     */
    policyBindings: Array<DingTalkAllowlistPolicyBinding>;
    /**
     *
     * @type {DingTalkAllowlistSourceLinkGuard}
     * @memberof DingTalkAllowlistStatusResponse
     */
    sourceLinkGuard: DingTalkAllowlistSourceLinkGuard;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistStatusResponse
     */
    callbackUrl: string;
}

/**
 * Check if a given object implements the DingTalkAllowlistStatusResponse interface.
 */
export function instanceOfDingTalkAllowlistStatusResponse(
    value: object,
): value is DingTalkAllowlistStatusResponse {
    if (!("revision" in value) || value["revision"] === undefined) return false;
    if (!("canManage" in value) || value["canManage"] === undefined) return false;
    if (!("config" in value) || value["config"] === undefined) return false;
    if (!("managedPolicy" in value) || value["managedPolicy"] === undefined) return false;
    if (!("policyBinding" in value) || value["policyBinding"] === undefined) return false;
    if (!("policyBindings" in value) || value["policyBindings"] === undefined) return false;
    if (!("sourceLinkGuard" in value) || value["sourceLinkGuard"] === undefined) return false;
    if (!("callbackUrl" in value) || value["callbackUrl"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistStatusResponseFromJSON(
    json: any,
): DingTalkAllowlistStatusResponse {
    return DingTalkAllowlistStatusResponseFromJSONTyped(json, false);
}

export function DingTalkAllowlistStatusResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        revision: json["revision"],
        canManage: json["can_manage"],
        config: json["config"],
        managedPolicy: DingTalkAllowlistManagedPolicyFromJSON(json["managed_policy"]),
        policyBinding: DingTalkAllowlistPolicyBindingFromJSON(json["policy_binding"]),
        policyBindings: (json["policy_bindings"] as Array<any>).map(
            DingTalkAllowlistPolicyBindingFromJSON,
        ),
        sourceLinkGuard: DingTalkAllowlistSourceLinkGuardFromJSON(json["source_link_guard"]),
        callbackUrl: json["callback_url"],
    };
}

export function DingTalkAllowlistStatusResponseToJSON(json: any): DingTalkAllowlistStatusResponse {
    return DingTalkAllowlistStatusResponseToJSONTyped(json, false);
}

export function DingTalkAllowlistStatusResponseToJSONTyped(
    value?: DingTalkAllowlistStatusResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        revision: value["revision"],
        can_manage: value["canManage"],
        config: value["config"],
        managed_policy: DingTalkAllowlistManagedPolicyToJSON(value["managedPolicy"]),
        policy_binding: DingTalkAllowlistPolicyBindingToJSON(value["policyBinding"]),
        policy_bindings: (value["policyBindings"] as Array<any>).map(
            DingTalkAllowlistPolicyBindingToJSON,
        ),
        source_link_guard: DingTalkAllowlistSourceLinkGuardToJSON(value["sourceLinkGuard"]),
        callback_url: value["callbackUrl"],
    };
}
