/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkUsageBucket
 */
export interface DingTalkUsageBucket {
    /**
     *
     * @type {string}
     * @memberof DingTalkUsageBucket
     */
    hourStart: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkUsageBucket
     */
    category: string;
    /**
     *
     * @type {number}
     * @memberof DingTalkUsageBucket
     */
    count: number;
    /**
     *
     * @type {number}
     * @memberof DingTalkUsageBucket
     */
    blockedCount: number;
}

/**
 * Check if a given object implements the DingTalkUsageBucket interface.
 */
export function instanceOfDingTalkUsageBucket(value: object): value is DingTalkUsageBucket {
    if (
        (!("hourStart" in (value as Record<string, any>)) &&
            !("hour_start" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["hourStart"] === undefined &&
            (value as Record<string, any>)["hour_start"] === undefined)
    )
        return false;
    if (!("category" in value) || value["category"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    if (
        (!("blockedCount" in (value as Record<string, any>)) &&
            !("blocked_count" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["blockedCount"] === undefined &&
            (value as Record<string, any>)["blocked_count"] === undefined)
    )
        return false;
    return true;
}

export function DingTalkUsageBucketFromJSON(json: any): DingTalkUsageBucket {
    return DingTalkUsageBucketFromJSONTyped(json, false);
}

export function DingTalkUsageBucketFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkUsageBucket {
    if (json == null) {
        return json;
    }
    return {
        hourStart: json["hour_start"],
        category: json["category"],
        count: json["count"],
        blockedCount: json["blocked_count"],
    };
}

export function DingTalkUsageBucketToJSON(json: any): DingTalkUsageBucket {
    return DingTalkUsageBucketToJSONTyped(json, false);
}

export function DingTalkUsageBucketToJSONTyped(
    value?: DingTalkUsageBucket | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        hour_start: value["hourStart"],
        category: value["category"],
        count: value["count"],
        blocked_count: value["blockedCount"],
    };
}
