/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistRemoveRequestRequest
 */
export interface DingTalkAllowlistRemoveRequestRequest {
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistRemoveRequestRequest
     */
    expectedRevision?: string | null;
}

/**
 * Check if a given object implements the DingTalkAllowlistRemoveRequestRequest interface.
 */
export function instanceOfDingTalkAllowlistRemoveRequestRequest(
    value: object,
): value is DingTalkAllowlistRemoveRequestRequest {
    return true;
}

export function DingTalkAllowlistRemoveRequestRequestFromJSON(
    json: any,
): DingTalkAllowlistRemoveRequestRequest {
    return DingTalkAllowlistRemoveRequestRequestFromJSONTyped(json, false);
}

export function DingTalkAllowlistRemoveRequestRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistRemoveRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        expectedRevision:
            json["expected_revision"] === undefined
                ? undefined
                : json["expected_revision"] === null
                  ? null
                  : json["expected_revision"],
    };
}

export function DingTalkAllowlistRemoveRequestRequestToJSON(
    json: any,
): DingTalkAllowlistRemoveRequestRequest {
    return DingTalkAllowlistRemoveRequestRequestToJSONTyped(json, false);
}

export function DingTalkAllowlistRemoveRequestRequestToJSONTyped(
    value?: DingTalkAllowlistRemoveRequestRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        expected_revision: value["expectedRevision"],
    };
}
