/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistPolicyBinding
 */
export interface DingTalkAllowlistPolicyBinding {
    /**
     *
     * @type {boolean}
     * @memberof DingTalkAllowlistPolicyBinding
     */
    _exists: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistPolicyBinding
     */
    pk: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkAllowlistPolicyBinding
     */
    enabled: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistPolicyBinding
     */
    target?: string;
}

/**
 * Check if a given object implements the DingTalkAllowlistPolicyBinding interface.
 */
export function instanceOfDingTalkAllowlistPolicyBinding(
    value: object,
): value is DingTalkAllowlistPolicyBinding {
    if (
        (!("_exists" in (value as Record<string, any>)) &&
            !("exists" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["_exists"] === undefined &&
            (value as Record<string, any>)["exists"] === undefined)
    )
        return false;
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("enabled" in value) || value["enabled"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistPolicyBindingFromJSON(json: any): DingTalkAllowlistPolicyBinding {
    return DingTalkAllowlistPolicyBindingFromJSONTyped(json, false);
}

export function DingTalkAllowlistPolicyBindingFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistPolicyBinding {
    if (json == null) {
        return json;
    }
    return {
        _exists: json["exists"],
        pk: json["pk"],
        enabled: json["enabled"],
        target: json["target"] == null ? undefined : json["target"],
    };
}

export function DingTalkAllowlistPolicyBindingToJSON(json: any): DingTalkAllowlistPolicyBinding {
    return DingTalkAllowlistPolicyBindingToJSONTyped(json, false);
}

export function DingTalkAllowlistPolicyBindingToJSONTyped(
    value?: DingTalkAllowlistPolicyBinding | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        exists: value["_exists"],
        pk: value["pk"],
        enabled: value["enabled"],
        target: value["target"],
    };
}
