/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkManagedUsersPagination
 */
export interface DingTalkManagedUsersPagination {
    /**
     *
     * @type {number}
     * @memberof DingTalkManagedUsersPagination
     */
    next: number;
    /**
     *
     * @type {number}
     * @memberof DingTalkManagedUsersPagination
     */
    previous: number;
    /**
     *
     * @type {number}
     * @memberof DingTalkManagedUsersPagination
     */
    count: number;
    /**
     *
     * @type {number}
     * @memberof DingTalkManagedUsersPagination
     */
    current: number;
    /**
     *
     * @type {number}
     * @memberof DingTalkManagedUsersPagination
     */
    totalPages: number;
    /**
     *
     * @type {number}
     * @memberof DingTalkManagedUsersPagination
     */
    pageSize: number;
}

/**
 * Check if a given object implements the DingTalkManagedUsersPagination interface.
 */
export function instanceOfDingTalkManagedUsersPagination(
    value: object,
): value is DingTalkManagedUsersPagination {
    if (!("next" in value) || value["next"] === undefined) return false;
    if (!("previous" in value) || value["previous"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    if (!("current" in value) || value["current"] === undefined) return false;
    if (
        (!("totalPages" in (value as Record<string, any>)) &&
            !("total_pages" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["totalPages"] === undefined &&
            (value as Record<string, any>)["total_pages"] === undefined)
    )
        return false;
    if (
        (!("pageSize" in (value as Record<string, any>)) &&
            !("page_size" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pageSize"] === undefined &&
            (value as Record<string, any>)["page_size"] === undefined)
    )
        return false;
    return true;
}

export function DingTalkManagedUsersPaginationFromJSON(json: any): DingTalkManagedUsersPagination {
    return DingTalkManagedUsersPaginationFromJSONTyped(json, false);
}

export function DingTalkManagedUsersPaginationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkManagedUsersPagination {
    if (json == null) {
        return json;
    }
    return {
        next: json["next"],
        previous: json["previous"],
        count: json["count"],
        current: json["current"],
        totalPages: json["total_pages"],
        pageSize: json["page_size"],
    };
}

export function DingTalkManagedUsersPaginationToJSON(json: any): DingTalkManagedUsersPagination {
    return DingTalkManagedUsersPaginationToJSONTyped(json, false);
}

export function DingTalkManagedUsersPaginationToJSONTyped(
    value?: DingTalkManagedUsersPagination | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        next: value["next"],
        previous: value["previous"],
        count: value["count"],
        current: value["current"],
        total_pages: value["totalPages"],
        page_size: value["pageSize"],
    };
}
