/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectorySyncStatus
 */
export interface DingTalkDirectorySyncStatus {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    corpId: string;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    status?: string;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectorySyncStatus
     */
    startedAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof DingTalkDirectorySyncStatus
     */
    finishedAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectorySyncStatus
     */
    error?: string;
    /**
     *
     * @type {any}
     * @memberof DingTalkDirectorySyncStatus
     */
    counters?: any | null;
}

/**
 * Check if a given object implements the DingTalkDirectorySyncStatus interface.
 */
export function instanceOfDingTalkDirectorySyncStatus(
    value: object,
): value is DingTalkDirectorySyncStatus {
    if (!("corpId" in value) || value["corpId"] === undefined) return false;
    return true;
}

export function DingTalkDirectorySyncStatusFromJSON(json: any): DingTalkDirectorySyncStatus {
    return DingTalkDirectorySyncStatusFromJSONTyped(json, false);
}

export function DingTalkDirectorySyncStatusFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectorySyncStatus {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
        status: json["status"] == null ? undefined : json["status"],
        startedAt: json["started_at"] == null ? undefined : new Date(json["started_at"]),
        finishedAt: json["finished_at"] == null ? undefined : new Date(json["finished_at"]),
        error: json["error"] == null ? undefined : json["error"],
        counters: json["counters"] == null ? undefined : json["counters"],
    };
}

export function DingTalkDirectorySyncStatusToJSON(json: any): DingTalkDirectorySyncStatus {
    return DingTalkDirectorySyncStatusToJSONTyped(json, false);
}

export function DingTalkDirectorySyncStatusToJSONTyped(
    value?: DingTalkDirectorySyncStatus | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
        status: value["status"],
        started_at:
            value["startedAt"] == null ? value["startedAt"] : value["startedAt"].toISOString(),
        finished_at:
            value["finishedAt"] == null ? value["finishedAt"] : value["finishedAt"].toISOString(),
        error: value["error"],
        counters: value["counters"],
    };
}
