/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkAllowlistApplyRequestRequest
 */
export interface DingTalkAllowlistApplyRequestRequest {
    /**
     *
     * @type {any}
     * @memberof DingTalkAllowlistApplyRequestRequest
     */
    config: any | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkAllowlistApplyRequestRequest
     */
    expectedRevision?: string | null;
}

/**
 * Check if a given object implements the DingTalkAllowlistApplyRequestRequest interface.
 */
export function instanceOfDingTalkAllowlistApplyRequestRequest(
    value: object,
): value is DingTalkAllowlistApplyRequestRequest {
    if (!("config" in value) || value["config"] === undefined) return false;
    return true;
}

export function DingTalkAllowlistApplyRequestRequestFromJSON(
    json: any,
): DingTalkAllowlistApplyRequestRequest {
    return DingTalkAllowlistApplyRequestRequestFromJSONTyped(json, false);
}

export function DingTalkAllowlistApplyRequestRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkAllowlistApplyRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        config: json["config"],
        expectedRevision: json["expected_revision"] == null ? undefined : json["expected_revision"],
    };
}

export function DingTalkAllowlistApplyRequestRequestToJSON(
    json: any,
): DingTalkAllowlistApplyRequestRequest {
    return DingTalkAllowlistApplyRequestRequestToJSONTyped(json, false);
}

export function DingTalkAllowlistApplyRequestRequestToJSONTyped(
    value?: DingTalkAllowlistApplyRequestRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        config: value["config"],
        expected_revision: value["expectedRevision"],
    };
}
