/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DingTalkDirectoryOrgContext
 */
export interface DingTalkDirectoryOrgContext {
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryOrgContext
     */
    corpId: string | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryOrgContext
     */
    userId: string | null;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryOrgContext
     */
    sourceSlug: string;
    /**
     *
     * @type {any}
     * @memberof DingTalkDirectoryOrgContext
     */
    departments: any | null;
    /**
     *
     * @type {any}
     * @memberof DingTalkDirectoryOrgContext
     */
    manager: any | null;
    /**
     *
     * @type {any}
     * @memberof DingTalkDirectoryOrgContext
     */
    managerChain: any | null;
    /**
     *
     * @type {boolean}
     * @memberof DingTalkDirectoryOrgContext
     */
    stale: boolean;
    /**
     *
     * @type {string}
     * @memberof DingTalkDirectoryOrgContext
     */
    lastSyncedAt: string | null;
}

/**
 * Check if a given object implements the DingTalkDirectoryOrgContext interface.
 */
export function instanceOfDingTalkDirectoryOrgContext(
    value: object,
): value is DingTalkDirectoryOrgContext {
    if (
        (!("corpId" in (value as Record<string, any>)) &&
            !("corp_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["corpId"] === undefined &&
            (value as Record<string, any>)["corp_id"] === undefined)
    )
        return false;
    if (
        (!("userId" in (value as Record<string, any>)) &&
            !("user_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["userId"] === undefined &&
            (value as Record<string, any>)["user_id"] === undefined)
    )
        return false;
    if (
        (!("sourceSlug" in (value as Record<string, any>)) &&
            !("source_slug" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["sourceSlug"] === undefined &&
            (value as Record<string, any>)["source_slug"] === undefined)
    )
        return false;
    if (!("departments" in value) || value["departments"] === undefined) return false;
    if (!("manager" in value) || value["manager"] === undefined) return false;
    if (
        (!("managerChain" in (value as Record<string, any>)) &&
            !("manager_chain" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["managerChain"] === undefined &&
            (value as Record<string, any>)["manager_chain"] === undefined)
    )
        return false;
    if (!("stale" in value) || value["stale"] === undefined) return false;
    if (
        (!("lastSyncedAt" in (value as Record<string, any>)) &&
            !("last_synced_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["lastSyncedAt"] === undefined &&
            (value as Record<string, any>)["last_synced_at"] === undefined)
    )
        return false;
    return true;
}

export function DingTalkDirectoryOrgContextFromJSON(json: any): DingTalkDirectoryOrgContext {
    return DingTalkDirectoryOrgContextFromJSONTyped(json, false);
}

export function DingTalkDirectoryOrgContextFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DingTalkDirectoryOrgContext {
    if (json == null) {
        return json;
    }
    return {
        corpId: json["corp_id"],
        userId: json["user_id"],
        sourceSlug: json["source_slug"],
        departments: json["departments"],
        manager: json["manager"],
        managerChain: json["manager_chain"],
        stale: json["stale"],
        lastSyncedAt: json["last_synced_at"],
    };
}

export function DingTalkDirectoryOrgContextToJSON(json: any): DingTalkDirectoryOrgContext {
    return DingTalkDirectoryOrgContextToJSONTyped(json, false);
}

export function DingTalkDirectoryOrgContextToJSONTyped(
    value?: DingTalkDirectoryOrgContext | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        corp_id: value["corpId"],
        user_id: value["userId"],
        source_slug: value["sourceSlug"],
        departments: value["departments"],
        manager: value["manager"],
        manager_chain: value["managerChain"],
        stale: value["stale"],
        last_synced_at: value["lastSyncedAt"],
    };
}
