/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkDirectoryUser } from "./DingTalkDirectoryUser";
import {
    DingTalkDirectoryUserFromJSON,
    DingTalkDirectoryUserToJSON,
} from "./DingTalkDirectoryUser";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedDingTalkDirectoryUserList
 */
export interface PaginatedDingTalkDirectoryUserList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedDingTalkDirectoryUserList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<DingTalkDirectoryUser>}
     * @memberof PaginatedDingTalkDirectoryUserList
     */
    results: Array<DingTalkDirectoryUser>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedDingTalkDirectoryUserList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedDingTalkDirectoryUserList interface.
 */
export function instanceOfPaginatedDingTalkDirectoryUserList(
    value: object,
): value is PaginatedDingTalkDirectoryUserList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedDingTalkDirectoryUserListFromJSON(
    json: any,
): PaginatedDingTalkDirectoryUserList {
    return PaginatedDingTalkDirectoryUserListFromJSONTyped(json, false);
}

export function PaginatedDingTalkDirectoryUserListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedDingTalkDirectoryUserList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(DingTalkDirectoryUserFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedDingTalkDirectoryUserListToJSON(
    json: any,
): PaginatedDingTalkDirectoryUserList {
    return PaginatedDingTalkDirectoryUserListToJSONTyped(json, false);
}

export function PaginatedDingTalkDirectoryUserListToJSONTyped(
    value?: PaginatedDingTalkDirectoryUserList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(DingTalkDirectoryUserToJSON),
        autocomplete: value["autocomplete"],
    };
}
