/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DingTalkDirectoryDepartment } from "./DingTalkDirectoryDepartment";
import {
    DingTalkDirectoryDepartmentFromJSON,
    DingTalkDirectoryDepartmentToJSON,
} from "./DingTalkDirectoryDepartment";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedDingTalkDirectoryDepartmentList
 */
export interface PaginatedDingTalkDirectoryDepartmentList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedDingTalkDirectoryDepartmentList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<DingTalkDirectoryDepartment>}
     * @memberof PaginatedDingTalkDirectoryDepartmentList
     */
    results: Array<DingTalkDirectoryDepartment>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedDingTalkDirectoryDepartmentList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedDingTalkDirectoryDepartmentList interface.
 */
export function instanceOfPaginatedDingTalkDirectoryDepartmentList(
    value: object,
): value is PaginatedDingTalkDirectoryDepartmentList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedDingTalkDirectoryDepartmentListFromJSON(
    json: any,
): PaginatedDingTalkDirectoryDepartmentList {
    return PaginatedDingTalkDirectoryDepartmentListFromJSONTyped(json, false);
}

export function PaginatedDingTalkDirectoryDepartmentListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedDingTalkDirectoryDepartmentList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(DingTalkDirectoryDepartmentFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedDingTalkDirectoryDepartmentListToJSON(
    json: any,
): PaginatedDingTalkDirectoryDepartmentList {
    return PaginatedDingTalkDirectoryDepartmentListToJSONTyped(json, false);
}

export function PaginatedDingTalkDirectoryDepartmentListToJSONTyped(
    value?: PaginatedDingTalkDirectoryDepartmentList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(DingTalkDirectoryDepartmentToJSON),
        autocomplete: value["autocomplete"],
    };
}
