# Generated by authentik for DingTalk directory cache.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_sources_oauth", "0013_useroauthsourceconnection_refresh_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="DingTalkDirectorySyncStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("corp_id", models.TextField()),
                ("status", models.TextField(default="unknown")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("counters", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_sources_oauth.oauthsource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "corp_id"], name="authentik_s_source__215220_idx"
                    ),
                    models.Index(fields=["status"], name="authentik_s_status_47a942_idx"),
                    models.Index(fields=["finished_at"], name="authentik_s_finishe_cee04c_idx"),
                ],
                "unique_together": {("source", "corp_id")},
            },
        ),
        migrations.CreateModel(
            name="DingTalkDirectoryDepartment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("corp_id", models.TextField()),
                ("dept_id", models.TextField()),
                ("name", models.TextField(blank=True, default="")),
                ("parent_dept_id", models.TextField(blank=True, default="")),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_sources_oauth.oauthsource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "corp_id", "dept_id"],
                        name="authentik_s_source__62216b_idx",
                    ),
                    models.Index(
                        fields=["source", "corp_id", "parent_dept_id"],
                        name="authentik_s_source__fc52ae_idx",
                    ),
                    models.Index(fields=["is_deleted"], name="authentik_s_is_dele_1cf0cd_idx"),
                ],
                "unique_together": {("source", "corp_id", "dept_id")},
            },
        ),
        migrations.CreateModel(
            name="DingTalkDirectoryUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("corp_id", models.TextField()),
                ("user_id", models.TextField()),
                ("union_id", models.TextField(blank=True, default="")),
                ("open_id", models.TextField(blank=True, default="")),
                ("name", models.TextField(blank=True, default="")),
                ("avatar", models.TextField(blank=True, default="")),
                ("title", models.TextField(blank=True, default="")),
                ("email", models.TextField(blank=True, default="")),
                ("mobile", models.TextField(blank=True, default="")),
                ("job_number", models.TextField(blank=True, default="")),
                ("manager_user_id", models.TextField(blank=True, default="")),
                ("dept_id_list", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_sources_oauth.oauthsource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "corp_id", "user_id"],
                        name="authentik_s_source__8b273a_idx",
                    ),
                    models.Index(
                        fields=["source", "corp_id", "manager_user_id"],
                        name="authentik_s_source__156a04_idx",
                    ),
                    models.Index(
                        fields=["source", "corp_id", "is_deleted"],
                        name="authentik_s_source__37e7aa_idx",
                    ),
                ],
                "unique_together": {("source", "corp_id", "user_id")},
            },
        ),
    ]
